site_name: Ligato Documentation
repo_url: https://github.com/ligato/docs.ligato.io

theme: readthedocs

nav:
- Home: index.md
- CNF: 'CNF/CNF-definition.md'
- CN Infra: 'Infra/cn-toc-file.md' 
- VPP Agent: 'user-guide/User-Guide.md'
- Tutorials: 'tutorials/README.md'
