site_name: Ligato Docs
site_url: https://docs.ligato.io/
site_description: Ligato documentation
site_author: Ligato Team

repo_url: https://github.com/ligato/docs

theme:
  name: readthedocs
  custom_dir: custom/
  highlightjs: true
  hljs_languages:
    - go
    - yaml

extra_css:
  - css/extra.css

nav:
- INTRODUCTION:
  - VPP-Agent: intro/agent.md
  - CNF definition: intro/cnf-definition.md
  - Overview: intro/overview.md
  - CN-Infra: intro/cn-toc-file.md
- USER GUIDE:
  - Quickstart guide: user-guide/quickstart.md
  - Learn how to: user-guide/learn-how-to.md
  - Concepts: user-guide/concepts.md
  - References: user-guide/references.md
  - Plugin overview: user-guide/plugin-overview.md
  - GoVPP Multiplexer: user-guide/govpp-multiplexer-plugin.md
  - VPP Interface plugin: user-guide/vpp-interface-plugin.md
  - VPP L2 plugin: user-guide/l2-plugin.md
  - VPP L3 plugin: user-guide/vpp-l3-plugin.md
  - Telemetry plugin: user-guide/telemetry-plugin.md
  - ACL plugin: user-guide/acl-plugin.md
  - IPSec plugin: user-guide/ipsec-plugin.md
  - NAT plugin: user-guide/nat-plugin.md
  - Punt plugin: user-guide/punt-plugin.md
  - Telemetry: user-guide/telemetry-plugin.md
  - Linux Interface plugin: user-guide/linux-interface-plugin.md
  - Linux L3 plugin: user-guide/linux-l3-plugin.md
  - Linux Namespaces: user-guide/linux-namespace-plugin.md
  - Connection plugins: user-guide/connection-plugins.md
  - Database plugins: user-guide/db-plugins.md
  - Framework plugins: user-guide/framework-plugins.md
  - ARM64: user-guide/arm64.md
- DEVELOPER GUIDE:
  - Agent: developer-guide/agent.md
  - Plugin lookup: developer-guide/plugin-lookup.md
  - KV Scheduler: developer-guide/kvscheduler.md
  - KV Descriptors: developer-guide/kvdescriptor.md
  - KVS Problem Solving: developer-guide/problem-solving.md
  - Go Docs: developer-guide/godocs.md
- TUTORIALS:
  - Hello World: tutorials/01_hello-world.md
  - Plugin Dependencies: tutorials/02_plugin-deps.md
  - REST Handler: tutorials/03_rest-handler.md
  - KV Datastore: tutorials/04_kv-store.md
  - KV Scheduler: tutorials/05_kv-scheduler.md
  - Plugin Lookup: tutorials/06_plugin-lookup.md
  - VPP Connection: tutorials/07_vpp-connection.md
  - GRPC Handler: tutorials/08_grpc-tutorial.md
- TESTING:
  - CSIT tests locally: testing/tests-locally.md
  - Robot framework guide: testing/robot-framework-guide.md
- TOOLS:
    - VPP-Agent-Ctl: tools/vpp-agent-ctl.md
- TROUBLESHOOTING:
  - FAQ: troubleshooting/faq.md

markdown_extensions:
  - extra
  - admonition
  - smarty
#  - codehilite Note: disabled for now since it breaks code fences, will be re-enabled later
  - def_list
  - toc:
      permalink: 
